### ISSUE TITLE
Todos items are not persisted between applications runs

### ISSUE THREAD

**Issue by stemberamichal** [chuva-io/TodoList#22]
- Deleted items still appear to be part of the list after restarting the application.
- Completed  items appear as not completed after restarting.

I'd suggest @ErickApps can solve this as it is connected to his issue #3 :)

**Comment by trismegis7us** [comment]
This will not be worked on. See the comment below.
https://github.com/chuva-io/TodoList/pull/24#issue-217479205

**Comment by trismegis7us** [comment]
This was thought to be a developer-related bug but is just a simulator issue.
